# Generated by Django 3.1.2 on 2020-10-07 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bid_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='pulbication_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
