# Generated by Django 3.1.2 on 2020-10-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201007_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='deadline',
        ),
    ]
