# Generated by Django 3.1.2 on 2020-10-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201010_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.TextField(),
        ),
    ]
