# Generated by Django 3.1.2 on 2020-10-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201010_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.FloatField(),
        ),
    ]
