# Generated by Django 3.1.2 on 2020-10-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201010_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='pulbication_date',
            field=models.DateTimeField(),
        ),
    ]
