# Generated by Django 3.1.2 on 2020-10-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20201010_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='comments',
            field=models.ManyToManyField(related_name='comments', to='auctions.Comment'),
        ),
    ]
